---
- hosts: localhost
  gather_facts: no
  module_defaults: 
    group/aws: 
      region: "us-west-2"
  tasks:
    - name: Create an ec2 launch template
      ec2_launch_template:
        name: "m6-ig-nginx-lt"
        image_id: "ami-026dea5602e368e96"
        key_name: auburnec2
        instance_type: t3.nano
        network_interfaces:
          - associate_public_ip_address: yes
            device_index: 0
            groups:
              - "{{ ig_development_sg.group_id }}"
              - "{{ nginx_sg.group_id }}"
              - "{{ ig_postgres_tag_sg.group_id }}"
        monitoring:
          enabled: yes
        iam_instance_profile: image-gallery-role
        tags:
          Name: m6-ig-asg-nginx
        user_data: "{{ lookup('file', './ec2_scripts/asg_bootscript.sh') | b64encode }}"
        disable_api_termination: false
      register: launch_template
    - name: debug
      debug: var=launch_template
    - ec2_asg:
        name: m6-image-gallery-asg
        availability_zones: [ 'us-west-2a', 'us-west-2b' ]
        vpc_zone_identifier: [ "{{ public_subnet.subnet.id }}", "{{ public_subnet2.subnet.id }}" ]
        launch_template:
          version: "{{ launch_template.latest_template.version_number }}"
          launch_template_name: "{{ launch_template.latest_template.launch_template_name }}"
          launch_template_id: "{{ launch_template.latest_template.launch_template_id }}"
        min_size: 1
        max_size: 2
        desired_capacity: 1
        target_group_arns: "{{ asg_ig_tag.target_group_arn }}"
        tags:
          - environment: production
            propagate_at_launch: no
            Name: m6-ig-asg
...