---
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: "ami-026dea5602e368e9"
  module_defaults: 
    group/aws: 
      region: "us-west-2"
  tasks:
    - name: Provision Dev EC2 Instance - configures RDS users/table/db on boot
      ec2:
        key_name: auburnec2
        group: [ "{{ ig_development_sg.group_name }}", "{{ nginx_sg.group_name }}", "{{ ig_postgres_tag_sg.group_name }}"]
        instance_type: t3.nano
        image: "{{ ami_id }}"
        instance_tags:
          Name: m6-ig-development
          Module: 6
          Department: DevOps
        monitoring: yes
        wait: yes
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        exact_count: 1
        user_data: "{{ lookup('file', './rds_scripts/configure_rds.sh') }}"
        count_tag:
          Name: m6-ig-development
        assign_public_ip: yes
        instance_profile_name: "image-gallery-role"
...