---
- hosts: localhost
  gather_facts: no
  vars:
    sec_postgres: {
        "username": "postgres",
        "password": "{{ lookup('password', '/tmp/m6_ig_pwds/postgres_user.txt') }}",
        "engine": "postgres",
        "host": "{{ rds_instance.instance.endpoint }}",
        "port": 5432,
        "dbInstanceIdentifier": "m6-ansible-image-gallery-rds",
      }
    sec_image_gallery: {
        "username": "image_gallery",
        "password": "{{ lookup('password', '/tmp/m6_ig_pwds/image_gallery_user.txt') }}",
        "engine": "postgres",
        "host": "{{ rds_instance.instance.endpoint }}",
        "port": 5432,
        "dbInstanceIdentifier": "m6-ansible-image-gallery-rds",
        "database_name": "image_gallery"
       }
  module_defaults:
    group/aws:
      region: "us-west-2"
  tasks:
    - name: Add postgres user to AWS Secrets Manager
      aws_secret:
        name: 'sec-ig-postgres'
        state: present
        secret_type: 'string'
        secret: '{{ sec_postgres | to_json }}'
        description: m6-postgres-user
    - name: Add image gallery user to AWS Secrets Manager
      aws_secret:
        name: 'sec-ig-image_gallery'
        state: present
        secret_type: 'string'
        secret: '{{ sec_image_gallery | to_json }}'
        description: m6-image_gallery-user
...