---
- hosts: localhost
  gather_facts: no
  module_defaults: 
    group/aws: 
      region: "us-west-2"
  tasks:
    - elb_target_group:
        name: m6-asg-ig-tag
        protocol: tcp
        port: 80
        vpc_id: "{{ vpc.vpc.id }}"
        stickiness_enabled: no
        stickiness_type: source_ip
        state: present
      register: asg_ig_tag
    - name: allocate a new elastic IP for Network Load Balancer - first EIP
      ec2_eip:
        in_vpc: yes
        release_on_disassociation: yes
      register: eip1
    - name: allocate a new elastic IP for Network Load Balancer - second EIP
      ec2_eip:
        in_vpc: yes
        release_on_disassociation: yes
      register: eip2
    - name: Update route53 DNS type A record with elastic IPs
      route53:
        state: present
        overwrite: yes
        region: us-west-2
        zone: sky-boston.com
        record: sky-boston.com
        identifier: sky-boston.com
        type: A
        ttl: 300
        value:
          - "{{ eip1.public_ip }}"
          - "{{ eip2.public_ip }}"
    - elb_network_lb:
        name: m6-ig-asg-lb
        subnet_mappings:
          - SubnetId: "{{ public_subnet.subnet.id }}"
            AllocationId: "{{ eip1.allocation_id }}"
          - SubnetId: "{{ public_subnet2.subnet.id }}"
            AllocationId: "{{ eip2.allocation_id }}"
        listeners:
          - Protocol: TCP # Required. The protocol for connections from clients to the load balancer (TCP or TLS) (case-sensitive).
            Port: 80 # Required. The port on which the load balancer is listening.
            DefaultActions:
              - Type: forward # Required. Only 'forward' is accepted at this time
                TargetGroupName: "{{ asg_ig_tag.target_group_name }}"    #m6-asg-ig-tag # Required. The name of the target group
          - Protocol: TLS # Required. The protocol for connections from clients to the load balancer (TCP or TLS) (case-sensitive).
            Port: 443 # Required for TLS traffic. Not a default setting.
            DefaultActions:
              - Type: forward # Required. Only 'forward' is accepted at this time
                TargetGroupName: "{{ asg_ig_tag.target_group_name }}"  # Required. The name of the target group
            Certificates:
              - CertificateArn: "{{ domain_cert.certificates[0].certificate_arn }}"
            SslPolicy: ELBSecurityPolicy-2016-08
        state: present
        wait: yes
      register: ig_nlb
...